# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: declension 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "declension"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Miks Mikelsons"]
  s.date = "2015-04-21"
  s.description = "Apply grammatical cases to words."
  s.email = "miks.mikelsons@gmail.com"
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "lib/declension.rb",
    "lib/declension/cases.rb",
    "lib/declension/core_ext.rb",
    "lib/declension/core_ext/string.rb",
    "lib/declension/languages.rb",
    "lib/declension/languages/base.rb",
    "lib/declension/languages/lv.rb",
    "lib/declension/languages/lv/inflections.rb",
    "lib/declension/version.rb",
    "lib/declension/word.rb",
    "lib/declension/wrappers.rb",
    "lib/declension/wrappers/string.rb"
  ]
  s.homepage = "http://github.com/miks/declension"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Apply grammatical cases to words"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

