# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "grammar_cases"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Miks Mikelsons"]
  s.date = "2015-04-15"
  s.description = "Apply grammatical cases to words."
  s.email = "miks.mikelsons@gmail.com"
  s.files = [
    "lib/grammar_cases.rb",
    "lib/grammar_cases/cases.rb",
    "lib/grammar_cases/core_ext.rb",
    "lib/grammar_cases/core_ext/string.rb",
    "lib/grammar_cases/languages.rb",
    "lib/grammar_cases/languages/base.rb",
    "lib/grammar_cases/languages/lv.rb",
    "lib/grammar_cases/languages/lv/inflections.rb",
    "lib/grammar_cases/version.rb",
    "lib/grammar_cases/word.rb",
    "lib/grammar_cases/wrappers.rb",
    "lib/grammar_cases/wrappers/string.rb"
  ]
  s.homepage = "http://github.com/miks/grammar_cases"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Apply grammatical cases to words"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

